#include "skp.h"
#ifndef SKP_PARSE_parser
#define SKP_PARSE_parser
extern char *skp_N_program;
void skp_R_program();
extern char *skp_N_expression;
void skp_R_expression();
extern char *skp_N_expr;
void skp_R_expr();
extern char *skp_N_let;
void skp_R_let();
extern char *skp_N_letvar;
void skp_R_letvar();
extern char *skp_N_letexpr;
void skp_R_letexpr();
extern char *skp_N_notkeyword;
void skp_R_notkeyword();
extern char *skp_N_keyword;
extern char *skp_N_lambda;
void skp_R_lambda();
extern char *skp_N_body;
void skp_R_body();
extern char *skp_N_args;
void skp_R_args();
extern char *skp_N_arg;
void skp_R_arg();
extern char *skp_N_atom;
void skp_R_atom();
extern char *skp_N_keyword;
extern char *skp_N_NUMBER;
void skp_R_NUMBER();
extern char *skp_N_STRING;
void skp_R_STRING();
extern char *skp_N_IDENTIFIER;
void skp_R_IDENTIFIER();
extern char *skp_N_NIL;
void skp_R_NIL();
extern char *skp_N_POPEN;
void skp_R_POPEN();
extern char *skp_N_PCLOSE;
void skp_R_PCLOSE();
extern char *skp_N_LAMBDA;
void skp_R_LAMBDA();
extern char *skp_N__;
void skp_R__();
extern char *skp_N_SPC_;
void skp_R_SPC_();
extern char *skp_N_EOF_;
void skp_R_EOF_();
#endif
