#include "skp.h"
#ifndef SKP_PARSE_parser
#define SKP_PARSE_parser
extern char *skp_N_program;
void skp_R_program();
extern char *skp_N_declaration;
void skp_R_declaration();
extern char *skp_N_classDecl;
void skp_R_classDecl();
extern char *skp_N_classbody;
void skp_R_classbody();
extern char *skp_N_funDecl;
void skp_R_funDecl();
extern char *skp_N_varDecl;
void skp_R_varDecl();
extern char *skp_N_classdef;
void skp_R_classdef();
extern char *skp_N_vardef;
void skp_R_vardef();
extern char *skp_N_classparent;
void skp_R_classparent();
extern char *skp_N_statement;
void skp_R_statement();
extern char *skp_N_exprStmt;
void skp_R_exprStmt();
extern char *skp_N_forStmt;
void skp_R_forStmt();
extern char *skp_N_ifStmt;
void skp_R_ifStmt();
extern char *skp_N_printStmt;
void skp_R_printStmt();
extern char *skp_N_returnStmt;
void skp_R_returnStmt();
extern char *skp_N_whileStmt;
void skp_R_whileStmt();
extern char *skp_N_block;
void skp_R_block();
extern char *skp_N_blkbody;
void skp_R_blkbody();
extern char *skp_N_expression;
void skp_R_expression();
extern char *skp_N_assignment;
void skp_R_assignment();
extern char *skp_N_assign_lhs;
void skp_R_assign_lhs();
extern char *skp_N_assign_rhs;
void skp_R_assign_rhs();
extern char *skp_N_logic_or;
void skp_R_logic_or();
extern char *skp_N_logic_and;
void skp_R_logic_and();
extern char *skp_N_equality;
void skp_R_equality();
extern char *skp_N_comparison;
void skp_R_comparison();
extern char *skp_N_term;
void skp_R_term();
extern char *skp_N_factor;
void skp_R_factor();
extern char *skp_N_unary;
void skp_R_unary();
extern char *skp_N_dotvalue;
void skp_R_dotvalue();
extern char *skp_N_fcall;
void skp_R_fcall();
extern char *skp_N_primary;
void skp_R_primary();
extern char *skp_N_OP_OR;
void skp_R_OP_OR();
extern char *skp_N_OP_AND;
void skp_R_OP_AND();
extern char *skp_N_OP_EQ;
void skp_R_OP_EQ();
extern char *skp_N_OP_CMP;
void skp_R_OP_CMP();
extern char *skp_N_OP_ADD;
void skp_R_OP_ADD();
extern char *skp_N_OP_MULT;
void skp_R_OP_MULT();
extern char *skp_N_OP_UNARY;
void skp_R_OP_UNARY();
extern char *skp_N_TRUE;
void skp_R_TRUE();
extern char *skp_N_FALSE;
void skp_R_FALSE();
extern char *skp_N_NIL;
void skp_R_NIL();
extern char *skp_N_THIS;
void skp_R_THIS();
extern char *skp_N_SUPER;
void skp_R_SUPER();
extern char *skp_N_function;
void skp_R_function();
extern char *skp_N_parameters;
void skp_R_parameters();
extern char *skp_N_arguments;
void skp_R_arguments();
extern char *skp_N_funcdef;
void skp_R_funcdef();
extern char *skp_N_parm;
void skp_R_parm();
extern char *skp_N_NUMBER;
void skp_R_NUMBER();
extern char *skp_N_STRING;
void skp_R_STRING();
extern char *skp_N_IDENTIFIER;
void skp_R_IDENTIFIER();
extern char *skp_N__;
void skp_R__();
extern char *skp_N_SPC_;
void skp_R_SPC_();
extern char *skp_N_EOF_;
void skp_R_EOF_();
#endif
